---
title: "Quadratic"
format: html
editor: visual
---

# Function for calculating bias and coverage

```{r}
#| echo: false
pacman::p_load("VIM","rgl","MASS","tidyverse","mice","MASS")
```

```{r}
calculate_metrics <-
  function(coefficients, true_beta, ci_value = 1.96) { # 1.96 ist der kritische Wert den wir brauchen alternativ kann man auch qnorm verwenden
    bias <- true_beta - coefficients$estimate

    ci_lower <- coefficients$estimate - ci_value / 2 * coefficients$std.error
    ci_upper <- coefficients$estimate + ci_value / 2 * coefficients$std.error
    cov <- ci_lower <= true_beta & true_beta <= ci_upper

    metrics <-
      cbind(coefficients, bias, cov) 
    # man könnte überlegen, auch noch die CI grenzen zu speichern
}
```

# Imputate missing data (Squared)

```{r}
results_of_all_methods <- list (
  "pmm_imp_first" = list(),
  "pmm_trans_first" = list(),
  "pmm_poly_method" = list(),# Da geht glaube ich nur mit pmmm (also default wird das verwendet)
  "rf_imp_first" = list(),
  "rf_trans_first" = list()#,
  #"cart_poly_com = list()
)

results_imp_first <- list()
results_trans_first <- list()

iterations <- 100 #1000
n_imp <- 5 #Hippel sagt 40 ?


for (i in 1:iterations) {
  set.seed(i)
  #### Daten erstellen----------------------------------------------------
  
  p <- 4  # 4 variables
  n <- 1000 # 3000 observations
  
  # draw expected values:
  mu <- (runif(p,-1,5))
  mu
  
  A <- matrix(rnorm(p^2), p, p)  # Zufällige Matrix
  A <- t(A) %*% A             # Positive definite Matrix
  V <- cov2cor(A)           # Korrelationmatrix
  
  # Datenframe
  x_df_org <- mvrnorm(n, mu, V) %>% data.frame()
  names(x_df_org) <- paste0("x_", 1:4)
  x_df_org$x1_squared <- x_df_org[, 1]^2 # transformiert
  mu[p+1] <- mu[1]^2
  
  true_beta <- c(1, 1.5, -0.8, 0.5, 0.2,0.4)  # c(intercept, b1,b2,b3,b4,b5(beta für interaktion))
  E_Y <- mu%*%true_beta[2:(p+2)]+true_beta[1] # Analytische Erwartungswerte
  
  # Empirische Y Werte
  x_matrix_org <- as.matrix(x_df_org)
  X_full <- cbind(1, x_matrix_org)  # Intercept hinzufügen
  
  Y <- X_full %*% true_beta + rnorm(n,0,1)
  data_sqrt<- cbind(x_df_org,Y)
  
  ### MAR Pattern-----------------------------------------------------
    data_sqrt_mar <- data_sqrt
  # Berechnung des fehlenden Mechanismus (MAR)
  miss_obs_x1 <- 0.5 + 2 * data_sqrt_mar$x_2 - 0.7 * data_sqrt_mar$x_3 +   rnorm(n, 0, 3)
  
  # Logischer Vektor für fehlende Werte
  mis_mar_p <- miss_obs_x1 < quantile(miss_obs_x1, 0.3)
  
  # Zuweisung von NA in x_1
  data_sqrt_mar$x_1[mis_mar_p] <- NA
  
  # Missingness bei x_1 squard durch NAs die Missing in x1 sind
  data_sqrt_mar$x1_squared <- data_sqrt_mar$x_1^2
  
  data <- data_sqrt_mar
  
  ##Impute, then transform----------------------------------------------

  #ImpData <- mice(data) # in den Daten ist die Transformierte Variable
  ImpData <- mice(data[, -which(names(data) == "x1_squared")], seed = i, m = n_imp)

  model_impute_first <- with(ImpData, lm(Y ~ x_1 + x_2 + x_3 + x_4 + I(x_1 ^ 2)))

  
  pooled_imp_first <- pool(model_impute_first)
  coeff_imp_first <- summary(pooled_imp_first)

  results_of_all_methods[["pmm_imp_first"]][[i]] <-
    calculate_metrics(coeff_imp_first, true_beta) #Frage: Reicht es diese Werte abzuspeichern oder brauchen wir noch mehr?

  #results <- list(coeffcients = coeff_imp_first, bias = bias_impute_first, coverage = cov_imp_first)


#   #Transform then impute----------------------------------
# 
#   data_with_transformed_variable <-
#     cbind(data, x1_squared <- data$x_1 ^ 2)
# 
#   #ImpDataTransFirst <- mice(data)
# 
# 
#   ### Idee:
  pred <- make.predictorMatrix(data)
  pred["x_1", "x1_squared"] <- 0
  pred["x1_squared", "x_1"] <- 0

  ImpDataTransFirst <- mice(data,pred = pred, print = FALSE, seed = i, m = n_imp)


  model_trans_first <-
    with(ImpDataTransFirst, lm(Y ~ x_1 + x_2 + x_3 + x_4 + x1_squared))
  pooled_trans_first <- pool(model_trans_first)
  coeff_trans_first <- summary(pooled_trans_first)


  results_of_all_methods[["pmm_trans_first"]][[i]] <-
    calculate_metrics(coeff_trans_first, true_beta)
  
  # Polynomialcombination
  ini <- mice(data, maxit = 0) # nur um Pred und Meth zu erstellen
  meth<- ini$method
  meth["x_1"] <- "quadratic"
  meth["x1_squared"] <- "~I(x_1^2)"
  pred <- ini$pred
  pred[, "x1_squared"] <- 0
  
  ImpData <- mice(data,method = meth,pred = pred,quad.outcome ="Y")
  model_poly_com <- with(ImpData, lm(Y ~ x_1 + x_2 + x_3 + x_4 + x1_squared))
  pooled_poly_com <- pool(model_poly_com)
  coeff_poly_com <- summary(pooled_poly_com)


  results_of_all_methods[["pmm_poly_method"]][[i]] <-
    calculate_metrics(coeff_poly_com, true_beta)
  
  # Impute, then transform (CART)-------------------
  
  ImpData <- mice(data[, -which(names(data) == "x1_squared")], method = "rf", seed = i, m = n_imp)

  model_impute_first <- with(ImpData, lm(Y ~ x_1 + x_2 + x_3 + x_4 + I(x_1 ^ 2)))

  
  pooled_imp_first <- pool(model_impute_first)
  coeff_imp_first <- summary(pooled_imp_first)

  results_of_all_methods[["rf_imp_first"]][[i]] <-
    calculate_metrics(coeff_imp_first, true_beta) 
  
  # Transform, then impute (CART)-------------------
  pred <- make.predictorMatrix(data)
  pred["x_1", "x1_squared"] <- 0
  pred["x1_squared", "x_1"] <- 0

  ImpDataTransFirst <- mice(data,method = "rf",pred = pred, print = FALSE, seed = i, m = n_imp)


  model_trans_first <-
    with(ImpDataTransFirst, lm(Y ~ x_1 + x_2 + x_3 + x_4 + x1_squared))
  pooled_trans_first <- pool(model_trans_first)
  coeff_trans_first <- summary(pooled_trans_first)


  results_of_all_methods[["rf_trans_first"]][[i]] <-
    calculate_metrics(coeff_trans_first, true_beta)
  
}

```

# Calculate averages over all iterations of one method

```{r}

all_average_results <- list()

for (method_name in names(results_of_all_methods)) {
  method <- results_of_all_methods[[method_name]]
  avg_results <- data.frame(estimate = numeric(0), bias = numeric(0), coverage = numeric(0))

  for (covariate in row.names(method[[1]])) {
    coefficient <- mean(sapply(method, function(df)
        df[covariate, "estimate"]))
    bias <- mean(sapply(method, function(df)
        df[covariate, "bias"]))
    coverage <- mean(sapply(method, function(df)
        df[covariate, "cov"]))

    # Create a new data frame for the row to bind
    new_row <- data.frame(estimate = coefficient, bias = bias, coverage = coverage)

    # Bind the row while preserving column names
    avg_results <- rbind(avg_results, new_row)

    # Assign the row name
    row.names(avg_results)[nrow(avg_results)] <- covariate
  }
  all_average_results[[method_name]] <- avg_results
}

```

# Zusammengefasste Ergebnisse

```{r}
covariates_names <- c("Intercept", "X1", "X2", "X3", "X4", "X^2")

# Alle Koeffizienten gemeinsam ausgeben
all_coefficients <- sapply(all_average_results, function(df)
  df[,"estimate"])
rownames(all_coefficients) <- covariates_names

# Alle Biases ausgeben
all_biases <- sapply(all_average_results, function(df)
  df[,"bias"])
rownames(all_biases) <- covariates_names


# Alle Coverages ausgeben
all_coverages <- sapply(all_average_results, function(df)
  df[,"coverage"])
rownames(all_coverages) <- covariates_names

```
